# Generated by Django 2.0 on 2020-04-17 08:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=True, populate_from='title', unique=True),
        ),
    ]
