# Generated by Django 2.0 on 2020-04-17 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200417_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 17, 58, 11, 517061)),
        ),
    ]
