# Generated by Django 2.0 on 2020-04-17 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200417_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 17, 18, 5, 27, 270857)),
        ),
    ]
