# Generated by Django 2.0 on 2020-04-18 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200418_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 18, 16, 50, 38, 549600)),
        ),
    ]
