# Generated by Django 2.0 on 2020-04-20 16:42

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200418_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='english_tite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='english_version_content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 22, 12, 10, 764100)),
        ),
    ]
