# Generated by Django 2.0 on 2020-04-20 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200420_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='english_tite',
            new_name='english_title',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 22, 24, 12, 729160)),
        ),
    ]
