# Generated by Django 2.0 on 2020-04-20 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200420_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 22, 39, 29, 920005)),
        ),
    ]
