# Generated by Django 2.0 on 2020-04-20 17:16

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200420_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 20, 22, 46, 54, 193114)),
        ),
        migrations.AlterField(
            model_name='article',
            name='english_version_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
