# Generated by Django 2.0 on 2020-04-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200421_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='english_version_content',
            new_name='Optional_english_version_content',
        ),
    ]
