# Generated by Django 2.0 on 2020-04-22 16:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0031_auto_20200422_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telugu_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('telugu_lyrics', ckeditor.fields.RichTextField()),
                ('english_lyrics', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True)),
                ('editing', models.BooleanField(default=False)),
                ('article_image', models.FileField(blank=True, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
