# Generated by Django 2.0 on 2020-04-22 16:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0032_lyrics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lyrics',
            new_name='Lyric',
        ),
    ]
