# Generated by Django 2.0 on 2020-04-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20200422_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='key',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
