# Generated by Django 2.0 on 2020-04-28 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_chord_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='live',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='live',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
