# Generated by Django 2.0 on 2020-04-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20200428_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='created_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
