# Generated by Django 2.0 on 2020-04-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_lyric_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='lyric',
            name='language',
            field=models.CharField(choices=[('TL', 'Freshman'), ('EN', 'Sophomore'), ('HN', 'Junior')], default='TL', max_length=2),
        ),
    ]
