# Generated by Django 2.0 on 2020-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20200428_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='language',
            field=models.CharField(choices=[('TL', 'Telugu'), ('EN', 'English'), ('HN', 'Hindi')], default='TL', max_length=2),
        ),
    ]
