# Generated by Django 2.0 on 2020-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_chord_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='composer',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='chord',
            name='singer',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='lyric',
            name='composer',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='lyric',
            name='singer',
            field=models.CharField(default='Unknown', max_length=150),
        ),
    ]
