# Generated by Django 2.0 on 2020-04-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20200428_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chord',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='lyric',
            name='article_image',
        ),
    ]
