# Generated by Django 2.0 on 2020-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_lyric_youtube_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='youtube_video',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
