# Generated by Django 2.0 on 2020-04-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_chord_youtube_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chord',
            old_name='youtube_video',
            new_name='youTube_video',
        ),
        migrations.RenameField(
            model_name='lyric',
            old_name='youtube_video',
            new_name='youTube_video',
        ),
    ]
